### ISSUE TITLE
Does it support Andorid or arm linux ?

### ISSUE THREAD

**Issue by hac425xxx** [bcoles/kasld#2]
Does it support Andorid or arm linux ?

**Comment by bcoles** [comment]
> Does it support Andorid or arm linux ?

I've never compiled and tested `kasld` on Android or ARM. Most of these techniques are orientated toward x86_64, but some should work with Android running on ARM (ie, reading `/proc/kallsyms` without `kptr_restrict`).

I intend to look into increasing support for both Android and ARM. Most of my ARM test devices are 32-bit ARMV7 with Android pre-KASLR kernels.

**Comment by bcoles** [comment]
KASLD now supports x86 (i386/i686), x86_64 (amd64), 32-bit arm (armv6l/armv7l) with limited support for 64-bit arm (armv8/aarch64/arm64).

KASLD also works with Android. You're on your own with cross-compiling, but dropping staticly linked executables on the host should also work.
